version: '3'
services:
  nginx:
    environment:
      - COMPASS_SSL_DOMAIN=${COMPASS_SSL_DOMAIN}
    image: nginx:1.23.0
    ports: 
      - 80:80
      - 443:443
    volumes:
      - certbot-www:/var/www/certbot:ro
      - certbot-conf:/etc/nginx/ssl:ro
      - ./html:/usr/share/nginx/html:ro
      - ./nginx/templates/https:/etc/nginx/templates
  certbot:
    environment:
      - REQUESTS_CA_BUNDLE=/etc/certs/combined.cer
    image: certbot/certbot:latest
    volumes:
      - certbot-www:/var/www/certbot/:rw
      - certbot-conf:/etc/letsencrypt/:rw
      - /usr/local/share/ca-certificates/combined.cer:/etc/certs/combined.cer:ro
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
volumes:
  certbot-www:
  certbot-conf: